export const TOKEN_IS_EXPIRED = 'TOKEN_IS_EXPIRED';
export const AUTH_PROFILE_RETRIEVAL_STARTED = 'AUTH_PROFILE_RETRIEVAL_STARTED';
export const AUTH_PROFILE_RETRIEVAL_COMPLETED = 'AUTH_PROFILE_RETRIEVAL_COMPLETED';
export const AUTH_PROFILE_RETRIEVAL_ERROR = 'AUTH_PROFILE_RETRIEVAL_ERROR';
